Revert "Use Clock in internal EventTracer"
This reverts commit ed6507b57e55cd3f1b590f0ae7df2c6bcab3c699.

Reason for revert: Hit problems in the chromium roll:
[62113/82444] CXX obj/remoting/host/remoting_me2me_host_static/remoting_me2me_host.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/remoting/host/remoting_me2me_host_static/remoting_me2me_host.o.d -DREMOT...(too long)
../../remoting/host/remoting_me2me_host.cc:2201:22: error: 'SetupInternalTracer' is deprecated: use SetupInternalTracer(const Environment&, bool) [-Werror,-Wdeprecated-declarations]
 2201 |     webrtc::tracing::SetupInternalTracer();
      |                      ^
../../third_party/webrtc/rtc_base/event_tracer.h:84:3: note: 'SetupInternalTracer' has been explicitly marked deprecated here
   84 | [[deprecated("use SetupInternalTracer(const Environment&, bool)")]]
      |   ^
1 error generated.
exit=1
error: cannot make progress due to previous 1 errors: exit=1


Original change's description:
> Use Clock in internal EventTracer
>
> This requires changes to X11 capturers due to a poorly defined macro in
> X11. 
>
> Bug: webrtc:42223992
> Change-Id: If9f8102386dc93142f9facfba21deb1f6a6a6964
> Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/445903
> Auto-Submit: Evan Shrubsole <eshr@webrtc.org>
> Commit-Queue: Tomas Gunnarsson <tommi@webrtc.org>
> Reviewed-by: Danil Chapovalov <danilchap@webrtc.org>
> Commit-Queue: Evan Shrubsole <eshr@webrtc.org>
> Reviewed-by: Tomas Gunnarsson <tommi@webrtc.org>
> Cr-Commit-Position: refs/heads/main@{#46819}

Bug: webrtc:42223992
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Icef9acd1413e9490fb5203fa607379404ace2d68
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/446760
Auto-Submit: Tomas Gunnarsson <tommi@webrtc.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#46825}