Revert "Switch to use 32 kHz processing inside APM"
This reverts commit 179be29133c50285dcbb4e273a0b6a42d265886c.

Reason for revert: Broke Chromium roll.

Error: https://ci.chromium.org/ui/p/chromium/builders/try/linux-rel/2423056/overview

Original change's description:
> Switch to use 32 kHz processing inside APM
>
> This CL switches to using 32 kHz processing internally inside WebRTC APM
> to avoid using the current 3-band split filter which has been shown to
> have issues with aliasing impacting the speech quality.
>
> The intention is to revert this change once the issues in the 3-band
> split filter have been addressed.
>
> Bug: webrtc:454695115
> Change-Id: Id87e7f8d2ba37a915b3640f7eeb5c996037c59aa
> Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/419860
> Commit-Queue: Per Åhgren <peah@webrtc.org>
> Reviewed-by: Henrik Lundin <henrik.lundin@webrtc.org>
> Cr-Commit-Position: refs/heads/main@{#46026}

Bug: webrtc:454695115
Change-Id: I599adf846217f0cb81588e84f541277465ef856a
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/420580
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Harald Alvestrand <hta@webrtc.org>
Reviewed-by: Per Åhgren <peah@webrtc.org>
Cr-Commit-Position: refs/heads/main@{#46037}